### ISSUE TITLE
Is resharers endpoint broken?

### ISSUE THREAD

**Issue by brainysmurf** [RomainVialard/Google-Plus-Community-Migrator#12]
I'm not saving any resharer info in the database. While debugging, it looks like the API might be broken? Steps to reproduce:

- Navigate to [Try this api](https://developers.google.com/+/web/api/rest/latest/activities/get) for the activities get method
- Enter: "z12igvdrasjmzdlsl22yuzmjjkvphtdmf" in activityId section
- Note the object.resharers.totalItems count is 1
- Navigate to [Try this api](https://developers.google.com/+/web/api/rest/latest/people/listByActivity) for the listByActivity method
- Enter "z12igvdrasjmzdlsl22yuzmjjkvphtdmf" in activityId section and select resharers for the collection
- Note that the result indicates 0 resharers

**Comment by RomainVialard** [comment]
Indeed, it doesn't seem to work for me either.

**Comment by brainysmurf** [comment]
Leaving resharers out.
