### ISSUE TITLE
nextPageToken returned in Activity List even when complete

### ISSUE THREAD

**Issue by brainysmurf** [RomainVialard/Google-Plus-Community-Migrator#14]
When reaching the end of the posts, I'm seeing this as the last result to activities feed:

Notice the nextPageToken is returned with some items:
{
    "nextPageToken": "ADSJ_i141D7ST18rQduQz-R1HCEaZM0uTbAsL-OfFn03Rxc6kHWHqPDC-CnkvRvPudDCeb9QqqaKiRJ7KKvSuUVEGB5HXERKf5L1VECcKVu4Ak3qZINGcuGFg7YXXg==",
    "items": [/* items */]
}

The very next return:
{
    "nextPageToken": "ADSJ_i0RS_5lv3C_O_VQuBKqN9KYTp4Wgc5zXD_jyUphhy3exzxE8zRvufKSOVUFBE6ndvnDPBHb97z6Ov_JrmavJBj-RGwAzusKErEV9v22exyJfoK9t-Tcbqo5b-38NErKKYL_bg==",
    "items": []
}

Consequence is that email never gets sent to user indicating complete. Workaround is to look for length of items to detect the operation has completed. Are you seeing the same thing??

**Comment by RomainVialard** [comment]
Yes, that's why there's this line in the current code:
https://github.com/RomainVialard/Google-Plus-Community-Migrator/blob/792846d94b3aa64457d1596b45082c58f612dc80/Apps%20Script/Code.js#L49

**Comment by brainysmurf** [comment]
Ah. Must have overlooked!
