### ISSUE TITLE
Not all Firebase projects are listed as options via the App Script dropdown

### ISSUE THREAD

**Issue by asmithasmith** [RomainVialard/Google-Plus-Community-Migrator#21]
Hello,

First of all, I truly appreciate the effort you have put into creating and supporting this solution. 

I am migrating various G+ communities, all public, all owned by the same domain. 
The first three Firebase projects I created ran through this importation process seamlessly.
Now I seem to be getting stuck; any new Firebase projects I create are not showing up in the Apps Script web app dropdown. 
Since the dropdown is available, I can not manually enter the Firebase project ID into the text field.
Is it possible I have hit a storage limitation? 
Many thanks!

**Comment by RomainVialard** [comment]
No, I think it's mostly a temporary issue on Google side: new projects can take a few minutes (hours?) to be detected via API and made visible in the Apps Script web app.
Can you check if they are visible now?

**Comment by asmithasmith** [comment]
Hi Romain,
I had thought that it might just be a delay in recognizing the project but the ones being excluding from the dropdown were created four days ago.
Just checking the App Script web app now and they still are not populating.🤔
Thanks for your help!
